server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # React Router를 위해 모든 경로를 index.html로 폴백 처리
        try_files $uri $uri/ /index.html;
    }
}
