spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://localhost:3306/freesia?serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

server:
  port: 8080

jwt:
  secret: freesia_project_secret_key_for_testing_purposes_only
  expiration: 86400000

ai:
  server:
    url: http://localhost:5000
    timeout-ms: 30000

jackson:
  time-zone: Asia/Seoul

youtube:
  api:
    key: dummy_key
    base-url: https://www.googleapis.com/youtube/v3
    max-results: 50
