spring:
  config:
    import: classpath:secret/
  profiles:
    active: secret

server:
  port: 8080

jwt:
  secret: freesia_project_secret_key_for_testing_purposes_only
  expiration: 86400000

ai:
  server:
    url: http://localhost:5000
    timeout-ms: 30000

jackson:
  time-zone: Asia/Seoul

youtube:
  api:
    key: AIzaSyBxKJGJJqJvJ8KqJvJ8KqJvJ8KqJvJ8KqJ
    base-url: https://www.googleapis.com/youtube/v3
    max-results: 50
